version: 2

registries:
  github-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "php"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "javascript"
  open-pull-requests-limit: 10
  registries:
  - github-registry

- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
    - "submodules"
  open-pull-requests-limit: 10
